development:
  adapter: postgresql
  encoding: unicode
  database: kozmeticar_dev
  pool: 5
  host: localhost
  username: ember
  password: "kozmeticar"

production:
  adapter: postgresql
  encoding: unicode
  database: kozmeticar_prod
  pool: 5
  host: localhost
  username: ember
  password: "kozmeticar"