development:
  adapter: postgresql
  encoding: unicode
  database: kozmeticar_development
  pool: 5
  host: localhost
  username: kozmeticar
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: kozmeticar_production
  pool: 5
  host: localhost
  username: kozmeticar
  password: 